# Generated by Django 4.2.7 on 2024-10-06 15:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserStreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField(unique=True)),
                ('streak', models.PositiveIntegerField(default=0)),
                ('last_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
