# Generated by Django 4.2.7 on 2024-10-15 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webApp", "0002_rename_streak_userstreak_current_streak_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserStreak",
        ),
    ]
