# Generated by Django 5.1.2 on 2024-10-31 21:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Course name, e.g., Math 101", max_length=100
                    ),
                ),
                ("start_time", models.TimeField(help_text="Course start time")),
                ("end_time", models.TimeField(help_text="Course end time")),
                (
                    "days_of_week",
                    models.CharField(
                        help_text="Days the course meets, e.g., Mon,Wed,Fri",
                        max_length=21,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="courses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
