# Generated by Django 5.1.2 on 2024-11-05 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courseApp", "0002_course_course_created_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="course_created_date",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Course created date and time"
            ),
        ),
    ]
