name: Black Autoformatting

on: [push, pull_request]

jobs:
  black-autoformatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: psf/black@stable
        with:
          options: "--check --verbose"
